# Use the official Miniconda3 image as the base image
FROM --platform=linux/amd64 continuumio/miniconda3:latest

RUN apt-get update && apt-get install -y libatomic1

# Set working directory in the container
WORKDIR /api

# Copy the 'environment.yml' file into the container
COPY environment.yml .
COPY requirements.txt .

# Create a new Conda environment from the 'environment.yml' file
RUN conda env create -f /api/environment.yml

# Ensure the Conda environment is activated
RUN echo "source activate gentrain" > ~/.bashrc
ENV PATH /opt/conda/envs/gentrain/bin:$PATH
# We need to define the PYTHONPATH as workers are located at /workers and still need access to the src module
ENV PYTHONPATH="$PYTHONPATH:/api"

# Copy the current directory contents into the container at the working directory
COPY . .

ENTRYPOINT ["/api/entrypoint.dev.sh"]