# Use the official Miniconda3 image as the base image
FROM continuumio/miniconda3:latest

ARG USER_ID=1001
ARG GROUP_ID=1001

# Set working directory in the container
WORKDIR /api

# Copy the 'environment.yml' file into the container
COPY environment.yaml /api

# Create a new Conda environment from the 'environment.yml' file
RUN conda env create -f /api/environment.yaml

RUN addgroup --gid $GROUP_ID gentrain
RUN adduser --disabled-password --uid $USER_ID --gid $GROUP_ID gentrain
RUN chown gentrain:gentrain -R /api
USER gentrain

RUN rm -rf /api/logs
RUN mkdir /api/logs

# Ensure the Conda environment is activated
RUN echo "source activate gentrain" > ~/.bashrc
ENV PATH /opt/conda/envs/gentrain/bin:$PATH
ENV PYTHONPATH="$PYTHONPATH:/"

# Copy the current directory contents into the container at the working directory
COPY --chown=gentrain . .

RUN prisma generate --generator py_client

# Make port 8080 available to the world outside this container
EXPOSE 8080

CMD ["gunicorn", "--chdir", "/", "--workers", "1", "--threads", "100", "--bind", ":8080", "api.server:app"]