# --- Stage 1: Build ---
FROM node:22-alpine 
WORKDIR /app

# Build-Argument
ARG VITE_API_HOST
ENV VITE_API_HOST=$VITE_API_HOST

# log $VITE_API_HOST
RUN echo "VITE_API_HOST is set to $VITE_API_HOST"

COPY package*.json ./
RUN npm ci
RUN npm i -g vite
COPY . .
CMD ["npm", "run", "build"]
