services:
  init:
    container_name: gentrain-init
    image: caddy:latest
    volumes:
      - type: bind
        source: ./init.prod.sh
        target: /init.prod.sh
      - type: volume
        source: caddy_data
        target: /data
      - type: volume
        source: caddy_config
        target: /config
      - type: bind
        source: ./caddy/certs
        target: /certs
      - type: volume
        source: api_data
        target: /api_data
    entrypoint: "/init.prod.sh"
    networks:
      - caddy
  caddy:
    container_name: gentrain-caddy
    # Use the caddy:latest image from Docker Hub
    image: caddy:latest
    # Use nobody user
    user: 65534:65534
    # Restart policy: restart the container unless explicitly stopped
    restart: unless-stopped
    # ports for Caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount the host Caddyfile
      - type: bind
        source: ./Caddyfile
        target: /etc/caddy/Caddyfile
        read_only: true
      - type: volume
        source: frontend_files
        target: /srv/frontend
      - type: volume
        source: docs_files
        target: /srv/documentation
      - type: bind
        source: ./caddy/certs
        target: /certs
        read_only: true
      - type: volume
        source: caddy_data
        target: /data
      - type: volume
        source: caddy_config
        target: /config
    networks:
      - caddy
    depends_on:
      frontend:
        condition: service_completed_successfully
      documentation:
        condition: service_completed_successfully
      api:
        condition: service_started
  redis:
    container_name: gentrain-redis
    image: gentrain-redis
    build:
      context: ./backend/redis
      dockerfile: Dockerfile.prod
    expose:
      - "${REDIS_PORT}"
    networks:
      - caddy
  db:
    container_name: gentrain-db
    image: postgres
    user: postgres:postgres
    hostname: localhost
    expose:
      - "${DATABASE_PORT}"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - caddy
  api:
    container_name: gentrain-api
    image: gentrain-api
    restart: unless-stopped
    depends_on:
      - redis
      - db
      - init
    volumes:
      - type: volume
        source: api_data
        target: /api/data
      - type: bind
        source: ./backend/prisma/schema.prisma
        target: /api/prisma/schema.prisma
    build:
      context: ./backend/api
      dockerfile: Dockerfile.prod
    expose:
      - "8080"
    env_file: ".env"
    environment:
      - DATABASE_URL=${DATABASE_DRIVER}://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    networks:
      - caddy
  worker:
    container_name: gentrain-worker
    image: gentrain-api:latest
    depends_on:
      - redis
    volumes:
      - type: volume
        source: api_data
        target: /api/data
      - type: bind
        source: ./backend/prisma/schema.prisma
        target: /api/prisma/schema.prisma
    entrypoint: "/api/workers/entrypoint.sh prod"
    links:
      - redis
      - init
    env_file: ".env"
    environment:
      - DATABASE_URL=${DATABASE_DRIVER}://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    networks:
      - caddy
  admin:
    container_name: gentrain-admin
    image: gentrain-admin
    build:
      context: ./backend/admin
      dockerfile: Dockerfile.prod
    volumes:
      - type: volume
        source: api_data
        target: /admin/data
      - type: bind
        source: ./backend/prisma/schema.prisma
        target: /admin/prisma/schema.prisma
    expose:
      - "4001"
    depends_on:
      - db
      - init
    env_file: ".env"
    environment:
      - DATABASE_URL=${DATABASE_DRIVER}://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?sslmode=disable
    networks:
      - caddy
  frontend:
    container_name: gentrain-frontend
    image: gentrain-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - type: volume
        source: frontend_files
        target: /app/dist
    networks:
      - caddy
    env_file: ".env"
    depends_on:
      api:
        condition: service_started

  documentation:
    container_name: gentrain-documentation
    image: gentrain-documentation
    build:
      context: ./documentation
      dockerfile: Dockerfile.prod
    volumes:
      - type: volume
        source: docs_files
        target: /documentation/build
    networks:
      - caddy

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
  api_data:
  docs_files:
  frontend_files:

networks:
  # Docker network for Caddy
  caddy:
