services:
  redis:
    container_name: gentrain-redis
    image: gentrain-redis
    build:
      context: ./backend/redis
      dockerfile: Dockerfile
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ./backend/redis/tls:/usr/local/etc/redis/tls
      - ./backend/redis/redis.conf:/usr/local/etc/redis/redis.conf
  redis-insight:
    container_name: gentrain-redis-insight
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
  db:
    container_name: gentrain-db
    image: postgres
    user: postgres:postgres
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    restart: unless-stopped
  api:
    container_name: gentrain-api
    image: gentrain-api
    restart: unless-stopped
    build:
      context: ./backend/api
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ./backend/api
        target: /api
      - type: bind
        source: ./backend/admin/prisma
        target: /api/prisma
      - type: bind
        source: ./backend/data/pathogen_schemes
        target: /api/pathogen_schemes
    depends_on:
      - redis
      - db
    env_file: ".env"
    environment:
      - DATABASE_URL=${DATABASE_DRIVER}://${DATABASE_USER}:${DATABASE_USER}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
  worker:
    container_name: gentrain-worker
    image: gentrain-api:latest
    depends_on:
      - redis
    entrypoint: /api/entrypoint-worker.sh
    volumes:
      - type: bind
        source: ./backend/api
        target: /api
    links:
      - redis
    env_file: ".env"
volumes:
  postgres_data:
