services:
  caddy:
    container_name: gentrain-caddy
    # Use the caddy:latest image from Docker Hub
    image: caddy:latest
    # Restart policy: restart the container unless explicitly stopped
    restart: unless-stopped
    # ports for Caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount the host Caddyfile
      - type: bind
        source: ./Caddyfile
        target: /etc/caddy/Caddyfile
        read_only: true
      - type: bind
        source: ./frontend/dist # Mount the build directory of the frontend so Caddy can serve the static files
        target: /srv
        read_only: true
      - type: volume
        source: caddy_data
        target: /data
      - type: volume
        source: caddy_config
        target: /config
    networks:
      - caddy
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started

  redis:
    container_name: gentrain-redis
    image: gentrain-redis
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - caddy

  db:
    container_name: gentrain-db
    image: postgres
    user: postgres:postgres
    hostname: localhost
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - caddy

  backend:
    container_name: gentrain-backend
    image: gentrain-backend
    restart: unless-stopped
    depends_on:
      - redis
      - db
    volumes:
      - type: bind
        source: ./backend/modules/sequence_analysis/schemes
        target: /home/backend/modules/sequence_analysis/schemes
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    env_file: ".env"
    networks:
      - caddy

  worker:
    container_name: gentrain-worker
    image: gentrain-backend:latest
    depends_on:
      - redis
    volumes:
      - type: bind
        source: ./backend/modules/sequence_analysis/schemes
        target: /home/backend/modules/sequence_analysis/schemes
    command: [ "supervisord", "-c", "/home/backend/supervisor.conf" ]
    links:
      - redis
    env_file: ".env"
    networks:
      - caddy

  frontend:
    container_name: gentrain-frontend
    image: gentrain-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - type: bind # Mount the dist directory to the frontend service
        source: ./frontend/dist
        target: /app/dist
    networks:
      - caddy
    env_file: ".env"
    depends_on:
      backend:
        condition: service_started

volumes:
  # persist data caddy_data
  caddy_data: # persist config caddy_config:
  caddy_config:
  postgres_data:

networks:
  # Docker network for Caddy
  caddy:
