# Use the official Miniconda3 image as the base image
FROM --platform=linux/amd64 continuumio/miniconda3:latest

# Set working directory in the container
WORKDIR /backend

# install clamav and init clamav-database for file validations
RUN apt-get update && apt-get install -y \
    clamav clamav-daemon clamav-freshclam \
    && rm -rf /var/lib/apt/lists/*
RUN freshclam
RUN mkdir /var/run/clamav
# Copy the 'environment.yml' file into the container
COPY environment.yaml .

# Create a new Conda environment from the 'environment.yml' file
RUN conda env create -f /backend/environment.yaml

# Ensure the Conda environment is activated
RUN echo "source activate gentrain" > ~/.bashrc
ENV PATH /opt/conda/envs/gentrain/bin:$PATH
ENV PYTHONPATH="$PYTHONPATH:/"

# Copy the current directory contents into the container at the working directory
COPY . .

ENTRYPOINT ["/backend/entrypoint-backend.sh"]