# Use the official Miniconda3 image as the base image
FROM continuumio/miniconda3:latest

ARG USER_ID=1001
ARG GROUP_ID=1001

# Set working directory in the container
WORKDIR /home/backend

# install clamav and init clamav-database for file validations
RUN apt-get update && apt-get install -y \
    clamav clamav-daemon clamav-freshclam \
    && rm -rf /var/lib/apt/lists/*
RUN freshclam
RUN mkdir /var/run/clamav

# Copy the 'environment.yml' file into the container
COPY environment.yaml /home/backend

# Create a new Conda environment from the 'environment.yml' file
RUN conda env create -f /home/backend/environment.yaml

RUN addgroup --gid $GROUP_ID gentrain
RUN adduser --disabled-password --uid $USER_ID --gid $GROUP_ID gentrain
RUN chown gentrain:gentrain -R /home/backend
USER gentrain

RUN rm -rf /home/backend/logs
RUN mkdir /home/backend/logs

# Ensure the Conda environment is activated
RUN echo "source activate gentrain" > ~/.bashrc
ENV PATH /opt/conda/envs/gentrain/bin:$PATH
ENV PYTHONPATH="$PYTHONPATH:/home"

# Copy the current directory contents into the container at the working directory
COPY --chown=gentrain . .

# Make port 8080 available to the world outside this container
EXPOSE 8080

RUN clamav-daemon start

CMD ["gunicorn", "--chdir", "/home", "--workers", "1", "--threads", "100", "--bind", ":8080", "backend.server:app"]