# Use the official Miniconda3 image as the base image
FROM --platform=linux/amd64 continuumio/miniconda3:latest

# Set working directory in the container
WORKDIR /app

# Copy the 'environment.yml' file into the container
COPY environment.yaml .


# Create a new Conda environment from the 'environment.yml' file
RUN conda env create -f /app/environment.yaml
# Ensure the Conda environment is activated
RUN echo "source activate dashboard" > ~/.bashrc
ENV PATH /opt/conda/envs/dashboard/bin:$PATH
ENV PYTHONUNBUFFERED=1

# Copy the current directory contents into the container at the working directory
COPY . .

RUN chmod +x /app/scripts/
RUN nextclade dataset get --name 'sars-cov-2' --output-dir '/app/datasets/nextclade_covid/'

# Declare /app as a mount point
VOLUME /app

# Set the FLASK_APP environment variable
ENV FLASK_ENV=development
ENV FLASK_APP=main_site.py

# Run the application
CMD ["flask", "run", "--host=0.0.0.0", "-p 4000"]