# Use the official Miniconda3 image as the base image
FROM continuumio/miniconda3:latest

# Set working directory in the container
WORKDIR /backend

# Copy the 'environment.yml' file into the container
COPY environment.yaml /backend

# Create a new Conda environment from the 'environment.yml' file
RUN conda env create -f /backend/environment.yaml

RUN mkdir /backend/backend
RUN mv /backend/!(backend) /backend/backend
RUN mv /backend/backend/uwsgi.ini /backend

# Create a new user 'uwsgi' and set it as the current user
RUN useradd -m uwsgi
USER uwsgi

# Ensure the Conda environment is activated
RUN echo "source activate dashboard" > ~/.bashrc
ENV PATH /opt/conda/envs/dashboard/bin:$PATH

# Copy the current directory contents into the container at the working directory
COPY --chown=uwsgi . .

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Run app.py when the container launches using uWSGI
ENTRYPOINT ["/backend/init_prod.sh"]