# Use the official Miniconda3 image as the base image
FROM --platform=linux/amd64 continuumio/miniconda3:latest

# Set working directory in the container
WORKDIR /app

# Copy the 'environment.yml' file into the container
COPY environment.yaml .


# Create a new Conda environment from the 'environment.yml' file
RUN conda env create -f /app/environment.yaml
# Ensure the Conda environment is activated
RUN echo "source activate dashboard" > ~/.bashrc
ENV PATH /opt/conda/envs/dashboard/bin:$PATH

# Copy the current directory contents into the container at the working directory
COPY . .

# Set the FLASK_APP environment variable
ENV FLASK_ENV=development
ENV FLASK_APP=main_site.py
ENV PYTHONUNBUFFERED=1

# Run the application
CMD ["flask", "run", "--host=0.0.0.0", "-p 4000"]