[supervisord]
nodaemon=true

[program:worker_viral]
directory=/
command=/opt/conda/envs/gentrain/bin/python -u /backend/worker_viral.py
numprocs=10
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
stderr_logfile=/backend/logs/worker_viral.err.log
stdout_logfile=/backend/logs/worker_viral.out.log

[program:worker_bacterial]
directory=/
command=/opt/conda/envs/gentrain/bin/python -u /backend/worker_bacterial.py
numprocs=3
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
stderr_logfile=/backend/logs/worker_bacterial.err.log
stdout_logfile=/backend/logs/worker_bacterial.out.log
