[supervisord]
nodaemon=true

[program:worker_viral]
directory=/home
command=/opt/conda/envs/gentrain/bin/python /home/backend/worker_viral.py
numprocs=6
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
stderr_logfile=/home/backend/logs/worker_viral.err.log
stdout_logfile=/home/backend/logs/worker_viral.out.log
user=uwsgi

[program:worker_bacterial]
directory=/home
command=/opt/conda/envs/gentrain/bin/python /home/backend/worker_bacterial.py
numprocs=26
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
stderr_logfile=/home/backend/logs/worker_bacterial.err.log
stdout_logfile=/home/backend/logs/worker_bacterial.out.log
user=uwsgi