[supervisord]
nodaemon=true

[program:flask_app]
directory=/
command=/opt/conda/envs/gentrain/bin/python /backend/server.py
process_name=flask_app
autostart=true
autorestart=true
stderr_logfile=/backend/logs/flask_app.err.log
stdout_logfile=/backend/logs/flask_app.out.log

[program:worker_viral]
directory=/
command=/opt/conda/envs/gentrain/bin/python /backend/worker_viral.py
numprocs=6
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
stderr_logfile=/backend/logs/worker_viral.err.log
stdout_logfile=/backend/logs/worker_viral.out.log

[program:worker_bacterial]
directory=/
command=/opt/conda/envs/gentrain/bin/python /backend/worker_bacterial.py
numprocs=6
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
stderr_logfile=/backend/logs/worker_bacterial.err.log
stdout_logfile=/backend/logs/worker_bacterial.out.log
