[uwsgi]                                                                                                                                   
http = :8080
chdir= /home
strict = true
vacuum = true
wsgi-file = backend/server.py
callable = app
master = true
processes = 5
buffer-size = 64000
die-on-term = true
pythonpath = /home/backend
http-websockets = true
gevent = 1000
gevent-monkey-patch= true