[uwsgi]                                                                                                                                   
http = :8080
wsgi-file = main_site.py
callable = app
master = true
processes = 5
buffer-size = 64000
die-on-term = true