[uwsgi]                                                                                                                                   
http = :8080
chdir= /home
wsgi-file = backend/server.py
callable = app
master = true
processes = 12
buffer-size = 64000
die-on-term = true
pythonpath = /home