[supervisord]
nodaemon=true

[program:worker_viral]
directory=/
command=/opt/conda/envs/gentrain/bin/python -u /api/workers/viral.py
numprocs=5
process_name=%(program_name)s_%(process_num)02d
autostart=true
stderr_logfile=/api/logs/worker_viral.err.log
stdout_logfile=/api/logs/worker_viral.out.log

[program:worker_bacterial]
directory=/
command=/opt/conda/envs/gentrain/bin/python -u /api/workers/bacterial.py
numprocs=1
process_name=%(program_name)s_%(process_num)02d
autostart=true
stderr_logfile=/api/logs/worker_bacterial.err.log
stdout_logfile=/api/logs/worker_bacterial.out.log
