[supervisord]
nodaemon=true

[program:worker_viral]
directory=/
command=/opt/conda/envs/gentrain/bin/python /api/src/workers/viral.py
numprocs=32
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
stderr_logfile=/api/logs/worker_viral.err.log
stdout_logfile=/api/logs/worker_viral.out.log
stdout_logfile_maxbytes=20MB
logfile_backups=3
user=gentrain

[program:worker_bacterial]
directory=/
command=/opt/conda/envs/gentrain/bin/python /api/src/workers/bacterial.py
numprocs=9
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
stderr_logfile=/api/logs/worker_bacterial.err.log
stdout_logfile=/api/logs/worker_bacterial.out.log
stdout_logfile_maxbytes=20MB
logfile_backups=3
user=gentrain