bind 0.0.0.0
requirepass "secret"
protected-mode yes
# rename commands to disable them
#rename-command CONFIG ""
#rename-command BGREWRITEAOF ""
#rename-command BGSAVE ""
#rename-command SAVE ""
#rename-command SPOP ""
#rename-command RENAME ""
#rename-command DEBUG ""
#rename-command FLUSHDB ""
#rename-command FLUSHALL ""
#rename-command PEXPIRE ""
#rename-command SHUTDOWN ""