[program:worker_viral]
command=python /home/backend/worker_viral.py
autostart=true
autorestart=true
stderr_logfile=/var/log/rq_high.err.log
stdout_logfile=/var/log/rq_high.out.log

[program:worker_bacterial]
command=python /home/backend/worker_bacterial.py
autostart=true
autorestart=true
stderr_logfile=/var/log/rq_low.err.log
stdout_logfile=/var/log/rq_low.out.log