[program:worker_high]
command=python /home/backend/worker.py high
autostart=true
autorestart=true
stderr_logfile=/var/log/rq_high.err.log
stdout_logfile=/var/log/rq_high.out.log

[program:worker_low]
command=python /home/backend/worker.py low
autostart=true
autorestart=true
stderr_logfile=/var/log/rq_low.err.log
stdout_logfile=/var/log/rq_low.out.log