from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Pathogen',
    'Role',
    'Session',
    'User',
    'Log',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Pathogen': {
    },
    'Role': {
        'users': 'User',
    },
    'Session': {
    },
    'User': {
        'role': 'Role',
    },
    'Log': {
    },
}

# fmt: on