FROM node:22-alpine

WORKDIR /admin

RUN apk add --no-cache openssl

# Set the environment variable for production
ENV NODE_ENV="production"

COPY package*.json ./

RUN npm ci --only=production

COPY . .

RUN npm i -g typescript

# Run the build command to compile TypeScript to JavaScript
RUN npm run build

# Generate Prisma client
RUN npx prisma generate --generator js_client

# Delete code from src because only the compiled code is nesseccary
RUN rm -rf src

# Expose the port the app runs on
EXPOSE 4001

CMD ["npm", "run", "start"]