FROM node:22-alpine

WORKDIR /admin

RUN apk add --no-cache openssl

ENV NODE_ENV="development"

COPY package*.json ./
RUN npm install

COPY . .

# Make entrypoint executable
RUN chmod +x entrypoint.sh

EXPOSE 4001

ENTRYPOINT ["./entrypoint.sh"]
