[supervisord]
nodaemon=true

[inet_http_server]
port=127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=http://127.0.0.1:9001

[program:clamd]
directory=/
command=clamd &
autostart=true
autorestart=false
stderr_logfile=/admin/logs/clamd.err.logs
stdout_logfile=/admin/logs/clamd.out.logs
stdout_logfile_maxbytes=20MB
logfile_backups=3
user=gentrain

[program:admin]
directory=/admin
command=npm run start
autostart=true
autorestart=false
stderr_logfile=/admin/logs/admin.err.logs
stdout_logfile=/admin/logs/admin.out.logs
stdout_logfile_maxbytes=20MB
logfile_backups=3
user=gentrain
