[supervisord]
nodaemon=true

[inet_http_server]
port=127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=http://127.0.0.1:9001

[program:clamd]
directory=/
command=clamd &
autostart=true
autorestart=false
stderr_logfile=/admin/logs/clamd.err.log
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
user=gentrain

[program:admin]
directory=/admin
command=npm run start
autostart=true
autorestart=true
stderr_logfile=/admin/logs/admin.err.log
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
user=gentrain
