site_name: GENTRAIN Docs
nav:
  - Application:
      - application/dashboard.md
      - application/data_management.md
      - application/outbreak_analysis.md
  - Admin:
      - admin/users.md
      - admin/pathogens.md
  - Developers:
      - developers/getting_started.md
      - developers/project_architecture.md
      - developers/deployment.md
      - developers/testing.md
      - developers/data_management.md
      - developers/security_and_data_privacy.md

extra_css:
  - assets/stylesheets/extra.css
theme:
  name: material
  logo: assets/img/gentrain-icon.png
  favicon: assets/img/gentrain-favicon.ico
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: custom
      accent: custom
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: custom
      accent: custom
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
copyright: © 2024 Universitätsklinikum Düsseldorf
