on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: connect and pull
        uses: appleboy/ssh-action@v1.0.3
        env:
          GENTRAIN_DIR: ${{ secrets.GENTRAIN_DIR }}
          GENTRAIN_PASSWORD: ${{ secrets.GENTRAIN_PASSWORD }}
          MAIN_BRANCH: ${{ secrets.MAIN_BRANCH }}
          VITE_HTBASIC_USERNAME: ${{ vars.HTBASIC_USERNAME }}
          VITE_HTBASIC_PASSWORD: ${{ secrets.HTBASIC_PASSWORD }}
          VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GENTRAIN_DIR,GENTRAIN_PASSWORD,MAIN_BRANCH
          script: |
            cd ${{ secrets.GENTRAIN_DIR }}
            git checkout ${{ secrets.MAIN_BRANCH }}
            git pull
            touch frontend/.env
            echo -e "VITE_HTBASIC_USERNAME=${{vars.HTBASIC_USERNAME}}" >> frontend/.env
            echo -e "VITE_HTBASIC_PASSWORD=${{vars.HTBASIC_PASSWORD}}" >> frontend/.env
            echo -e "VITE_API_BASE_URL=${{vars.API_BASE_URL}}" >> frontend/.env
            touch backend/.env
            echo -e "FLASK_ENV=${{vars.FLASK_ENV}}" >> backend/.env
            echo -e "FLASK_APP=main_script.py" >> backend/.env
            echo -e "PYTHONUNBUFFERED=1" >> backend/.env
            echo ${{ secrets.GENTRAIN_PASSWORD }} | sudo -S docker compose -f docker-compose.prod.yaml stop
            echo ${{ secrets.GENTRAIN_PASSWORD }} | sudo -S docker compose -f docker-compose.prod.yaml up -d --no-deps --build
            exit
