on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  frontend_build:
    name: Frontend Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      - name: Build
        run: |
          cd frontend
          npm run build
      - name: Notify Slack Action Success
        uses: ravsamhq/notify-slack-action@2.3.0
        env:
          SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
        if: always()
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "Frontend Build"
          icon_failure: 💥
  documentation_build:
    name: Documentation Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: |
          cd documentation
          npm ci
      - name: Build
        run: |
          cd documentation
          npm run build
      - name: Notify Slack Action Success
        uses: ravsamhq/notify-slack-action@2.3.0
        env:
          SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
        if: always()
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "Frontend Build"
          icon_failure: 💥
  pull_production_state:
    name: Pull Production State
    runs-on: ubuntu-latest
    needs:
      - frontend_build
      - documentation_build

    steps:
      - name: Pull latest version
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd ${{ vars.GENTRAIN_DIR }}
            git checkout ${{ vars.PRODUCTION_BRANCH }}
            git pull
            exit
      - name: Notify Slack Action Success
        uses: ravsamhq/notify-slack-action@2.3.0
        env:
          SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
        if: always()
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "Pull Production State"
          icon_failure: 💥

  restart_docker_containers:
    name: Restart Docker Containers
    runs-on: ubuntu-latest
    needs: pull_production_state

    steps:
      - name: Generate environment variables
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd ${{ vars.GENTRAIN_DIR }}
            rm -f .env
            touch .env
            echo -e "VITE_API_HOST=${{vars.VITE_API_HOST}}" >> .env
            echo -e "APP_ENV=${{vars.PROD_APP_ENV}}" >> .env
            echo -e "APP_URL=${{vars.APP_URL}}" >> .env
            echo -e "REDIS_HOST=${{vars.REDIS_HOST}}" >> .env
            echo -e "REDIS_PORT=${{vars.REDIS_PORT}}" >> .env
            echo -e "REDIS_USERNAME=${{vars.REDIS_USERNAME}}" >> .env
            echo -e "REDIS_PASSWORD=${{secrets.REDIS_PASSWORD}}" >> .env
            echo -e "DATABASE_DRIVER=${{vars.DATABASE_DRIVER}}" >> .env
            echo -e "DATABASE_NAME=${{vars.DATABASE_NAME}}" >> .env
            echo -e "DATABASE_HOST=${{vars.DATABASE_HOST}}" >> .env
            echo -e "DATABASE_PORT=${{vars.DATABASE_PORT}}" >> .env
            echo -e "DATABASE_USER=${{vars.DATABASE_USER}}" >> .env
            echo -e "DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}}" >> .env
            echo -e "DEFAULT_ADMIN_USERNAME=${{vars.DEFAULT_ADMIN_USERNAME}}" >> .env
            echo -e "DEFAULT_ADMIN_PASSWORD=${{secrets.DEFAULT_ADMIN_PASSWORD}}" >> .env
            echo -e "COOKIE_SECRET=${{secrets.COOKIE_SECRET}}" >> .env
            echo -e "SESSION_SECRET=${{secrets.SESSION_SECRET}}" >> .env
            echo -e "ADMIN_PANEL_PORT=${{vars.ADMIN_PANEL_PORT}}" >> .env
            echo -e "ADMIN_PANEL_URL=${{vars.ADMIN_PANEL_URL}}" >> .env
            echo -e "API_DATA_DIRECTORY=${{vars.API_DATA_DIRECTORY}}" >> .env
            echo -e "ADMIN_HTBASIC_USERNAME=${{vars.ADMIN_HTBASIC_USERNAME}}" >> .env
            echo -e "ADMIN_HTBASIC_PASSWORD=${{secrets.PROD_ADMIN_HTBASIC_PASSWORD}}" >> .env
            exit
      - name: Restart docker containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd ${{ vars.GENTRAIN_DIR }}
            echo ${{ secrets.GENTRAIN_PASSWORD }} | sudo -S mkdir -p db_dumps
            echo ${{ secrets.GENTRAIN_PASSWORD }} | sudo -S ls -1t db_dumps/ | tail -n +5 | xargs -I {} rm -f db_dumps/{}
            echo ${{ secrets.GENTRAIN_PASSWORD }} | sudo -S docker exec -t gentrain-db pg_dump -d ${{vars.DATABASE_NAME}} -U ${{vars.DATABASE_USER}} > db_dumps/dump_`date +%Y-%m-%d"_"%H_%M_%S`.sql
            echo ${{ secrets.GENTRAIN_PASSWORD }} | sudo -S docker compose -f docker-compose.prod.yaml down
            echo ${{ secrets.GENTRAIN_PASSWORD }} | sudo -S docker system prune -f
            echo ${{ secrets.GENTRAIN_PASSWORD }} | sudo -S docker compose -f docker-compose.prod.yaml build --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g)
            echo ${{ secrets.GENTRAIN_PASSWORD }} | sudo -S docker compose -f docker-compose.prod.yaml up -d
            exit
      - name: Notify Slack Action Success
        uses: ravsamhq/notify-slack-action@2.3.0
        env:
          SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
        if: always()
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "Restart Docker Container"
          icon_failure: 💥
      - name: Notify Slack Action Success
        uses: ravsamhq/notify-slack-action@2.3.0
        env:
          SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
        if: always()
        with:
          status: ${{ job.status }}
          notify_when: "success"
          notification_title: "Production Deployment"
          icon_success: 🚀
