on:
  push:
    branches:
      - production

jobs:
  test_frontend_build:
    name: Test Frontend Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build
      - name: Notify Slack Action Success
        uses: ravsamhq/notify-slack-action@2.3.0
        env:
          SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
        if: always()
        with:
          status: ${{ job.status }}
          notify_when: "success,failure"
          notification_title: "Frontend Build"
          icon_success: 🚀
          icon_failure: 💥

  pull_production_state:
    name: Pull Production State
    runs-on: ubuntu-latest
    needs: test_frontend_build

    steps:
      - name: Pull latest version
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd ${{ vars.GENTRAIN_DIR }}
            git checkout ${{ vars.MAIN_BRANCH }}
            git pull
            exit

  restart_docker_containers:
    name: Restart Docker Containers
    runs-on: ubuntu-latest
    needs: pull_production_state

    steps:
      - name: Generate environment variables
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd ${{ vars.GENTRAIN_DIR }}
            rm frontend/.env backend/.env
            touch frontend/.env
            echo -e "VITE_HTBASIC_USERNAME=${{vars.HTBASIC_USERNAME}}" >> frontend/.env
            echo -e "VITE_HTBASIC_PASSWORD=${{secrets.HTBASIC_PASSWORD}}" >> frontend/.env
            echo -e "VITE_API_BASE_URL=${{vars.API_BASE_URL}}" >> frontend/.env
            touch backend/.env
            echo -e "FLASK_ENV=${{vars.FLASK_ENV}}" >> backend/.env
            exit
      - name: Restart docker containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd ${{ vars.GENTRAIN_DIR }}
            echo ${{ secrets.GENTRAIN_PASSWORD }} | sudo -S docker compose -f docker-compose.prod.yaml down
            echo ${{ secrets.GENTRAIN_PASSWORD }} | sudo -S docker system prune -f
            echo ${{ secrets.GENTRAIN_PASSWORD }} | sudo -S docker compose -f docker-compose.prod.yaml build --no-cache
            echo ${{ secrets.GENTRAIN_PASSWORD }} | sudo -S docker compose -f docker-compose.prod.yaml up -d
            exit
      - name: Notify Slack Action Success
        uses: ravsamhq/notify-slack-action@2.3.0
        env:
          SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
        if: always()
        with:
          status: ${{ job.status }}
          notify_when: "success,failure"
          notification_title: "Production Deployment"
          icon_success: 🚀
          icon_failure: 💥
