on:
  push:
    branches:
      - e2e-testing
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-24.04 # Server version

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build all Docker images
        run: docker compose -f docker-compose.test.yaml build

      - name: Start Docker Containers
        run: docker compose -f docker-compose.test.yaml up -d

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: e2e-tests/cypress/videos

      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: e2e-tests/cypress/screenshots

      - name: Shut down containers
        if: always()
        run: docker compose down -v
