on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-24.04 # Server version

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build all Docker images
        run: docker compose -f docker-compose.test.yaml build

      - name: Start Docker Containers
        run: docker compose -f docker-compose.test.yaml up -d

        #docker compose -f docker-compose.test.yaml run --rm e2e-tests npx cypress run --browser chrome --spec "cypress/e2e/app/tutorial*.spec.ts"
        #docker compose -f docker-compose.test.yaml run --rm e2e-tests npx cypress run --browser chrome --spec "cypress/e2e/smoke/smoke*.spec.ts"

      - name: Shut down containers
        if: always()
        run: docker compose down -v
